name: Build and Publish Docker Image AMD

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/masa-finance/subtensor/${{ github.ref_name }}
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile.masa --tag $IMAGE_NAME:amd-latest --push .

